<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WEBMLCI_02_Corporate Credit Marketing (Code CCM)</name>
   <tag></tag>
   <elementGuidId>cbf462a5-462c-4b84-a200-6d85205c3156</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.tab-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion']/div/div/h4/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>d1f7803e-1442-41b4-a9b7-adc9db60e4bb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-title</value>
      <webElementGuid>7493bf17-29f2-4b54-ad86-b3e4e4a91ce7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Corporate Credit Marketing (Code : CCM)</value>
      <webElementGuid>173c8c25-9bd6-40c5-bc76-ff0a6f1da050</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]/span[@class=&quot;tab-title&quot;]</value>
      <webElementGuid>bc6b6ba5-9d06-4327-9f6f-7e829c26a870</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div/div/h4/a/span[2]</value>
      <webElementGuid>29f1882a-3959-45e5-8802-60d3f75ae429</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Karir'])[2]/following::span[2]</value>
      <webElementGuid>372f23b8-2643-4641-8c1a-1149c621eb15</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Possessed at least Bachelor’s Degree in any major.'])[1]/preceding::span[1]</value>
      <webElementGuid>ad7b642b-053f-4b48-b731-dfc568afb506</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Maximum 30 years old.'])[1]/preceding::span[1]</value>
      <webElementGuid>5f84d63d-cf8b-45bb-a989-e71aed6b0475</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Corporate Credit Marketing (Code : CCM)']/parent::*</value>
      <webElementGuid>a74b4df0-a6c4-4f3a-8d6c-ff621b8b3bbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a/span[2]</value>
      <webElementGuid>342ee55a-315c-4d56-9829-e64a92058cd3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Corporate Credit Marketing (Code : CCM)' or . = 'Corporate Credit Marketing (Code : CCM)')]</value>
      <webElementGuid>b8eed5bc-b9c4-4d25-83eb-e15e8068a50c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
