<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_LOGOUT</name>
   <tag></tag>
   <elementGuidId>eb5c436b-a409-4477-b027-da088c12d7c7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span > a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[contains(text(),'LOGOUT')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>ce4e7158-520f-475f-aacf-6b597655a339</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>logout.php?log=1</value>
      <webElementGuid>ec9e74c2-6d49-4e88-ac25-4bbf085603ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>LOGOUT</value>
      <webElementGuid>6bc81368-e494-4240-885d-e12e1eeb9a10</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/table[1]/tbody[1]/tr[2]/td[2]/span[1]/a[1]</value>
      <webElementGuid>14b2b273-8039-4be7-a7b8-49ec3b293780</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'LOGOUT')]</value>
      <webElementGuid>10a2b7bc-5432-4683-8db2-de727a47840f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Individual Assessment Uncreated Report'])[1]/following::a[1]</value>
      <webElementGuid>f1e7c458-66ca-4ef2-a6b6-cc5dad16acaa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='E-SKPR BCA'])[1]/preceding::a[1]</value>
      <webElementGuid>a726ab1f-c533-430d-850b-e125c578a4db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Account Name'])[1]/preceding::a[1]</value>
      <webElementGuid>d90561b0-3480-4e9f-98c7-337495ea7432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='LOGOUT']/parent::*</value>
      <webElementGuid>e3fb7d65-bd88-4d80-9895-88fec424b5bf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'logout.php?log=1')]</value>
      <webElementGuid>44cd362d-b588-4314-bd5a-929f44972fc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//span/a</value>
      <webElementGuid>0a1151e7-d7a8-4776-aa74-5b39c6aa70b0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'logout.php?log=1' and (text() = 'LOGOUT' or . = 'LOGOUT')]</value>
      <webElementGuid>0718cc34-c58e-4c56-9fb6-77eee9714ec2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
