<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Name in ID Card</name>
   <tag></tag>
   <elementGuidId>4cb3fb0c-819f-48a7-b323-a8a05bab2e33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='frm1']/table/tbody/tr[2]/td/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>0dfdc5c7-d7e0-406c-8497-984ee2967daf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:popup('ro_list_cust.php?id1=I&amp;id2=1&amp;id3=&amp;id4=1&amp;id5=2&amp;id6=New&amp;id7=3', '800', '800')</value>
      <webElementGuid>04d60d27-2a4d-4306-ba85-a4d2b99f92bd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>9837a89b-6d93-493f-8f9c-2a43b3e384cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Name in ID Card</value>
      <webElementGuid>bafe0e80-463e-461c-9e19-8f032e90cc83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;frm1&quot;)/table[1]/tbody[1]/tr[2]/td[1]/a[1]</value>
      <webElementGuid>49c37502-cf22-4320-b5d0-231200418e20</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MLCI - Credit Approval Memorandum/iframe_Member_main</value>
      <webElementGuid>c401ba51-f48c-4ad7-a006-5a51b579d608</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm1']/table/tbody/tr[2]/td/a</value>
      <webElementGuid>97d8062e-c827-4b14-9df8-4ba0fe77f6d6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Name in ID Card')]</value>
      <webElementGuid>163ffeef-27d1-40e7-8f11-2730ffe9c3fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Detail Information'])[1]/following::a[1]</value>
      <webElementGuid>37d7a431-909b-48cd-9ee0-43aba0e98412</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='(i)'])[1]/preceding::a[1]</value>
      <webElementGuid>aa329ce5-d83c-41e4-92b8-04b27301a7da</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer No.'])[1]/preceding::a[1]</value>
      <webElementGuid>848588d8-a014-4c42-8879-31e9fd96802a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Name in ID Card']/parent::*</value>
      <webElementGuid>d90fd770-e0cb-4d43-9b6f-586a04678474</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, &quot;javascript:popup('ro_list_cust.php?id1=I&amp;id2=1&amp;id3=&amp;id4=1&amp;id5=2&amp;id6=New&amp;id7=3', '800', '800')&quot;)]</value>
      <webElementGuid>1ff54a54-9509-4903-9c90-dbcedcef45c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>cf285b11-3889-4620-acc8-4027a94872fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = concat(&quot;javascript:popup(&quot; , &quot;'&quot; , &quot;ro_list_cust.php?id1=I&amp;id2=1&amp;id3=&amp;id4=1&amp;id5=2&amp;id6=New&amp;id7=3&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;800&quot; , &quot;'&quot; , &quot;, &quot; , &quot;'&quot; , &quot;800&quot; , &quot;'&quot; , &quot;)&quot;) and (text() = 'Name in ID Card' or . = 'Name in ID Card')]</value>
      <webElementGuid>9a1923fe-063b-4227-acdf-9b19c718ff19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
