<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Next</name>
   <tag></tag>
   <elementGuidId>977dc7c1-8114-4a3b-99d3-afa83d35cc6d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btnnext</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btnnext']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>3e7f9d39-d630-419d-bf96-0d456b0b53dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>d0c6dae2-9f64-4a50-8221-59a95897291d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>task</value>
      <webElementGuid>d9f86894-ff46-4b3d-9bef-d5690534d881</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>496f9050-be00-43a4-8886-c67a60f6eb50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btnnext</value>
      <webElementGuid>1572965a-3225-4162-b5e5-8d8ebd4df1f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Next >> </value>
      <webElementGuid>9560b66d-b82e-4093-9287-a55656253d36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btnnext&quot;)</value>
      <webElementGuid>4ed1b77c-1bad-4eb9-aea5-b8b8d43988d8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MLCI - Credit Approval Memorandum/iframe_Member_main</value>
      <webElementGuid>0a5a1a85-50bf-4b59-8d96-c1fa161a11c3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btnnext']</value>
      <webElementGuid>bfaba9ae-2df5-4c56-89bc-62089dadebb4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='frm1']/button</value>
      <webElementGuid>a9a3970f-0a5a-401d-8548-5743aa4c658c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Survey By'])[1]/following::button[1]</value>
      <webElementGuid>9334d46f-4c1b-4c63-a026-de01791aae01</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Review Date'])[1]/following::button[1]</value>
      <webElementGuid>5f17f6ba-784e-404c-870c-7ca390bebf2e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('id(', '&quot;', 'btnnext', '&quot;', ')')])[1]/preceding::button[1]</value>
      <webElementGuid>2e3416c1-f450-417f-aaa1-16a9e04dd476</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Next >>']/parent::*</value>
      <webElementGuid>26c3b160-b847-4055-9894-ac8537df1e2c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button</value>
      <webElementGuid>27c67681-36be-4e54-8927-ab8acc129a4c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'submit' and @name = 'task' and @id = 'btnnext' and (text() = ' Next >> ' or . = ' Next >> ')]</value>
      <webElementGuid>45ec7cd9-c352-4f32-8952-788453da4551</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
