<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>iframe_Member_main</name>
   <tag></tag>
   <elementGuidId>bef3a393-7d74-4d2a-9bb3-f43ed2611dc9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#main</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//iframe[@id='main']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>iframe</value>
      <webElementGuid>757f1c0d-3de7-4f1d-8806-149c2095c956</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>cefb073f-3424-45cf-ad6c-5021e4b4a6ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>main</value>
      <webElementGuid>a45065a4-c3fd-4810-a6ec-ffa0aeed2043</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>100%</value>
      <webElementGuid>fb8f6f98-9cdb-434c-b734-0a8fb6b8b472</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginheight</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>35b28280-5ce7-448a-b872-386457a90b2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>marginwidth</name>
      <type>Main</type>
      <value>5</value>
      <webElementGuid>d5ee154d-f3c5-4baf-aa00-a6bbaa0d224e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>frameborder</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>768594e6-42fd-4ef4-94b9-cdf7793c7de5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>cust_detail.php?menu=1&amp;submenu=1&amp;hal=cust_detail.php&amp;id1=I&amp;id2=1&amp;id3=&amp;id4=1&amp;id5=2&amp;id6=New&amp;id7=3&amp;id8=&amp;id9=NEW&amp;id11=1&amp;id12=undefined&amp;apless=&amp;applno=&amp;ins_loan=0&amp;z=&amp;fleg=&amp;id13=undefined</value>
      <webElementGuid>39db8e0f-00fa-4791-a0e4-04401cc8bfcf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>scrolling</name>
      <type>Main</type>
      <value>no</value>
      <webElementGuid>bfaa0db4-a837-45d1-b282-f104244873a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onload</name>
      <type>Main</type>
      <value>javascript:resizeIframe(this);</value>
      <webElementGuid>5ec61448-0e3d-4cd9-b81d-b0e12b15836e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;main&quot;)</value>
      <webElementGuid>ce33eab5-fd76-4a33-b55e-cb08e30c256a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//iframe[@id='main']</value>
      <webElementGuid>27270227-ad0c-4a60-9232-f834f72458db</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//iframe</value>
      <webElementGuid>c8f3edaa-4712-4ba7-8c89-3272d016cb55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//iframe[@name = 'main' and @id = 'main' and @src = 'cust_detail.php?menu=1&amp;submenu=1&amp;hal=cust_detail.php&amp;id1=I&amp;id2=1&amp;id3=&amp;id4=1&amp;id5=2&amp;id6=New&amp;id7=3&amp;id8=&amp;id9=NEW&amp;id11=1&amp;id12=undefined&amp;apless=&amp;applno=&amp;ins_loan=0&amp;z=&amp;fleg=&amp;id13=undefined']</value>
      <webElementGuid>f0b31135-8e16-4784-bc22-5a1b7f7e03b7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
