<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img</name>
   <tag></tag>
   <elementGuidId>d3792aad-f8c7-4959-a64d-bc1d72289369</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[title=&quot;Home&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//img[@onclick=&quot;window.location='../index.php?sumber=module_cam/cam_onhand.php'&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>8d33880f-4546-4df9-aac5-0b6d218d25f0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>../images/home.png</value>
      <webElementGuid>d31d9e59-ec03-4f6b-a2f2-851e75dada9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>window.location='../index.php?sumber=module_cam/cam_onhand.php'</value>
      <webElementGuid>93a304eb-e629-4a3b-8d9f-4c4a582399a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Home</value>
      <webElementGuid>5ac4c33d-86bb-43c5-9ef3-ca972b05bbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cssmenu&quot;)/ul[1]/li[8]/img[1]</value>
      <webElementGuid>1a859487-46b4-4224-8885-c29b5357f1e4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//img[@onclick=&quot;window.location='../index.php?sumber=module_cam/cam_onhand.php'&quot;]</value>
      <webElementGuid>6d52047a-fa53-4c3c-85c1-142348a29fa8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cssmenu']/ul/li[8]/img</value>
      <webElementGuid>e62815ce-ff90-43d1-8eff-d8d4fd8c71f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@title='Home']</value>
      <webElementGuid>e2e3deda-a38c-470e-b456-c5c8d7ce3e4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//img</value>
      <webElementGuid>e18c1441-e3c9-47d2-87d4-19b06e9bd8a6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = '../images/home.png' and @title = 'Home']</value>
      <webElementGuid>ed351440-c655-4de5-a3d6-0357d2da0d33</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
