<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoYes_boa</name>
   <tag></tag>
   <elementGuidId>25872816-913f-45af-965e-a9289aa0edbe</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#owner_nonavail</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='owner_nonavail']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>d4b339b6-4c68-442b-9552-428fd60e6168</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8f60021d-8f64-4ad0-8b23-8164686d2fc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>owner_nonavail</value>
      <webElementGuid>c22d530f-b69c-4c29-a01e-b3530d3585e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>boa</value>
      <webElementGuid>35078ee2-df12-4339-aa37-604e5ab4e021</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>f650e805-3f10-48fa-a773-39fe8a800458</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;owner_nonavail&quot;)</value>
      <webElementGuid>abdc0747-0b46-4956-828d-26842ba8def8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>c1831de3-2044-41f3-b529-a92020ff74f5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='owner_nonavail']</value>
      <webElementGuid>397515c8-0223-4d1b-bd83-726297e262ee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[19]/td/input</value>
      <webElementGuid>ebbe0ab7-f377-4a68-9e04-5adebdfca0ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @id = 'owner_nonavail' and @name = 'boa']</value>
      <webElementGuid>735ed8ee-a41a-4452-8ea5-43a32e9e8b04</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
