<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_IndividuCorporate_ind_cor</name>
   <tag></tag>
   <elementGuidId>96450cb4-df76-4817-a98d-4173b806403e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Ind</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='Ind']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>fd284be5-50d0-40ca-aa4b-77760e885115</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>8d9769c2-942e-4b67-b494-c11a0aa619aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>ind_cor</value>
      <webElementGuid>c652bca5-bfa0-45ef-93cb-a38621803c88</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Ind</value>
      <webElementGuid>f26fa1f2-9ca9-4cfb-9ac7-7775aa80cece</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>d4a949d8-81f6-48d0-bf35-9faa305e861f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onclick</name>
      <type>Main</type>
      <value>publicgo(this.value);</value>
      <webElementGuid>150649d1-01f4-4d26-aeb5-d8214600c898</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Ind&quot;)</value>
      <webElementGuid>cc733719-69f8-420f-b6de-b2fa3acc7405</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>dda23138-4c64-4049-9e39-619f424dd1fe</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='Ind']</value>
      <webElementGuid>38afc218-e50c-42c8-aa31-f3e8857b8227</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>61dc6330-6e94-4513-8740-31d87d383f59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'ind_cor' and @id = 'Ind']</value>
      <webElementGuid>cef92524-8725-40c7-a3eb-9c1c53a8640d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
