<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Multiguna_yes</name>
   <tag></tag>
   <elementGuidId>11523112-b2cd-4580-bfea-68ee00d7ce57</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#yes</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='yes']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>e054bcf8-db93-46a3-9cba-a2ded6dfe0ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>submit</value>
      <webElementGuid>28de89e7-915b-49bf-b8ca-f9f57f220500</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>bce551b9-39fc-4b34-abe3-6e7fba38a65e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>yes</value>
      <webElementGuid>e205f7e0-fbab-46f7-a9fd-a905c1e1c2a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>Yes</value>
      <webElementGuid>13f72d69-98b6-4a52-8d8a-20a4d514d4f2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;yes&quot;)</value>
      <webElementGuid>404e4053-f0aa-46a9-8725-fc2577157d94</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/Page_MLCI - Credit Approval Memorandum/iframe_LOGOUT_main1</value>
      <webElementGuid>99742054-9c4b-4b6e-b3cd-2aa7c53ef204</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='yes']</value>
      <webElementGuid>5929961b-050c-43b7-a313-a331b7a46fbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='dialoga']/table/tbody/tr[6]/td/input</value>
      <webElementGuid>31afe224-79df-4959-958f-6bbfc7bedfc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[6]/td/input</value>
      <webElementGuid>1d197ebc-49a8-40f0-b9ff-57a19b196ad3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'submit' and @name = 'yes' and @id = 'yes']</value>
      <webElementGuid>6ef05a55-3888-4a23-8785-9f6ee1709395</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
