<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>WEBMLCI_07_Bagaimana cara pelunasan fasilitas pembiayaan</name>
   <tag></tag>
   <elementGuidId>009cb90f-c772-46e2-932e-8a541dae6082</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='accordion']/div[6]/div/h4/a/span[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>5af2e36c-4ebb-4808-a83b-ab1543af0453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tab-title</value>
      <webElementGuid>74e173d1-9ef9-4b41-9e66-cf154c8475a3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Bagaimana cara pelunasan fasilitas pembiayaan</value>
      <webElementGuid>8fc54b1c-5e7c-4677-a1da-033122c74afb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;accordion&quot;)/div[@class=&quot;panel panel-default&quot;]/div[@class=&quot;panel-heading&quot;]/h4[@class=&quot;panel-title&quot;]/a[@class=&quot;collapsed&quot;]/span[@class=&quot;tab-title&quot;]</value>
      <webElementGuid>17805dd5-1404-4c85-8b0a-bbce5aa20623</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='accordion']/div[6]/div/h4/a/span[2]</value>
      <webElementGuid>741e723f-6319-4c33-9144-7d16225dd0e5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Kapan pembayaran angsuran dilakukan?'])[1]/following::span[2]</value>
      <webElementGuid>ce864b2e-bfbc-4150-81ea-105a79834327</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bilyet Giro *)'])[1]/following::span[4]</value>
      <webElementGuid>82f35b7a-c2db-4e61-a196-0f250692989d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bagaimana cara pembayaran angsuran?'])[1]/preceding::span[2]</value>
      <webElementGuid>25ddbdb2-a471-4a0b-9cf2-cba4a92afd00</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Mengapa Mitsui Leasing ?'])[1]/preceding::span[4]</value>
      <webElementGuid>f2b8a1bb-cae5-4dfa-9ea6-515cf5e1bb66</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Bagaimana cara pelunasan fasilitas pembiayaan']/parent::*</value>
      <webElementGuid>356fab4d-4cdb-4dab-9387-9946170189d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div/h4/a/span[2]</value>
      <webElementGuid>ca8b867f-56d0-434f-b842-8ee8f5f9f321</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Bagaimana cara pelunasan fasilitas pembiayaan' or . = 'Bagaimana cara pelunasan fasilitas pembiayaan')]</value>
      <webElementGuid>db1b43b3-8b61-4b6e-a9b8-a918630f31b1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
