<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add CAM</name>
   <tag></tag>
   <elementGuidId>8a54939a-78ec-4e52-80c4-48f136221b2d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li/ul/li/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>64603e2a-8240-48d2-ab55-e843086a8785</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_cam/index.php?menu_id=1.1</value>
      <webElementGuid>4bc66402-3925-4896-9792-58afa68e45b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>d452e269-6f87-4d27-92c4-de3c08928b11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add CAM</value>
      <webElementGuid>f20480ff-b8d5-4e1c-bb5e-c4ff8408584e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[1]/a[1]</value>
      <webElementGuid>df551ee5-d3f6-4dbb-9594-347cc581a841</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li/ul/li/a</value>
      <webElementGuid>385b9cda-c257-4252-9289-0f3940217145</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add CAM')]</value>
      <webElementGuid>c38ee1ed-5fbe-469f-b2a6-05a314aacedd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='On Hand'])[1]/preceding::a[1]</value>
      <webElementGuid>0e644934-7bd9-4526-b64c-ec9309adbe2d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add CAM']/parent::*</value>
      <webElementGuid>78b32fe5-b30f-4bd4-a4dd-1ea06accabb2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_cam/index.php?menu_id=1.1')]</value>
      <webElementGuid>a9cb4579-be5f-4dad-9007-aaa841363053</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a</value>
      <webElementGuid>16d1fa4f-a3cd-44ab-8ef1-45a64d385eee</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_cam/index.php?menu_id=1.1' and (text() = 'Add CAM' or . = 'Add CAM')]</value>
      <webElementGuid>e8ba6ca6-3b15-4169-9759-801fbd85e7df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
