<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Customer Overdue BPKB 90 Days</name>
   <tag></tag>
   <elementGuidId>ac444456-0ebd-4d2d-9300-2693e0cd6d0f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//ul[@id='treemenu2']/li/ul/li[3]/ul/li[9]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>9026174c-f8df-4520-85b5-d3a67aa0a91d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>module_cam/cust_overdueBPKB.php?menu_id=1.4.9</value>
      <webElementGuid>70a55e88-487f-43eb-b450-5470abe9fe62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>main1</value>
      <webElementGuid>442d4a38-1906-4828-8271-0241fadd6d07</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Customer Overdue BPKB >90 Days</value>
      <webElementGuid>062b37b4-de58-49ed-8c84-b045f46f5ed2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;treemenu2&quot;)/li[@class=&quot;submenu&quot;]/ul[1]/li[@class=&quot;submenu&quot;]/ul[1]/li[9]/a[1]</value>
      <webElementGuid>078b6f81-fda3-4926-ab87-ca743f32c748</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='treemenu2']/li/ul/li[3]/ul/li[9]/a</value>
      <webElementGuid>49dd9bbe-2426-4fc0-87db-185b2a1f65c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Customer Overdue BPKB >90 Days')]</value>
      <webElementGuid>a1e8c466-6f3b-4c7e-ba97-267828d81a6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Retained Commission CAM'])[1]/following::a[1]</value>
      <webElementGuid>b14b11db-b13e-4795-9c8d-a0b0d0cea6f0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Amortization Report'])[1]/following::a[2]</value>
      <webElementGuid>2da6ba53-39b4-4ff2-9531-3ca98311e742</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add Restructuring for Covid 19'])[1]/preceding::a[1]</value>
      <webElementGuid>3137857d-8558-4041-800a-e4b008751dc5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Customer Overdue BPKB >90 Days']/parent::*</value>
      <webElementGuid>d5f5b3f5-5767-4f4a-a8cb-28e531b9ff7f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'module_cam/cust_overdueBPKB.php?menu_id=1.4.9')]</value>
      <webElementGuid>4c1c9ff2-eae0-4734-ae7f-aa3ad4a6ffd7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[9]/a</value>
      <webElementGuid>ddfc78f2-f19f-47e4-960e-adbf6a494e55</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'module_cam/cust_overdueBPKB.php?menu_id=1.4.9' and (text() = 'Customer Overdue BPKB >90 Days' or . = 'Customer Overdue BPKB >90 Days')]</value>
      <webElementGuid>19eba9bd-8058-4462-b41d-d1997bd0c3d2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
