<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_UsedNew_new_car</name>
   <tag></tag>
   <elementGuidId>c52c1429-f2a6-4be0-bda7-3e7d14a7786f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#new</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='new']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5518e24d-0ac5-4c1f-831c-fbe04ab6884e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>561e1479-5708-416d-a953-90ea680e1be0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>new_car</value>
      <webElementGuid>5c154298-da95-43d2-b726-429662279f21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>new</value>
      <webElementGuid>55cb68c4-4a4a-47cd-b8ea-2fa5ad6358a4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>e3435911-c754-4be7-9e22-d4598203a4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;new&quot;)</value>
      <webElementGuid>549d7392-aebc-48dc-bd0e-aec830c17a30</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/REP05_WEBMLCI_AC_FAQ/iframe_LOGOUT_main1</value>
      <webElementGuid>7adbf410-5e91-4929-b020-38f38fc2733f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='new']</value>
      <webElementGuid>f88cd06b-b132-44a6-b2bd-8bc26a9bcf39</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[13]/td/input[2]</value>
      <webElementGuid>ee6bf3b1-0358-4c13-8a2e-4f903b22a699</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'new_car' and @id = 'new']</value>
      <webElementGuid>28e8901e-c72c-485a-b84e-339bf878c375</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
