<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_NoYes_guarantor</name>
   <tag></tag>
   <elementGuidId>10194686-4736-4478-b428-a5cf4deac085</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;guarantor&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='guarantor']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>71600485-6b3e-4b2f-85b7-f5efd35a9ab5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>radio</value>
      <webElementGuid>ecba6db2-d7a5-4b80-a259-56a1870fcc24</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>guarantor</value>
      <webElementGuid>d3e4410c-eb34-4362-9578-77366fa2df97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>707db902-7865-4bc4-97ea-ee918dec795b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]/form[1]/table[1]/tbody[1]/tr[15]/td[1]/input[1]</value>
      <webElementGuid>c204c1ba-5838-4aa8-ad1d-a0fe40292b66</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>ref_element</name>
      <type>Main</type>
      <value>Object Repository/REP05_WEBMLCI_AC_FAQ/iframe_LOGOUT_main1</value>
      <webElementGuid>3848f986-784c-41e8-9dd8-1833134deddc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='guarantor']</value>
      <webElementGuid>75047a00-aedb-4602-97ab-036ead4f3ad9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//tr[15]/td/input</value>
      <webElementGuid>49752dbb-eca9-4cbb-ad39-ebee65256fac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'radio' and @name = 'guarantor']</value>
      <webElementGuid>2d73d646-9e76-4517-83c4-283a5dfd6adf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
